[tool.poetry]
name = "shibabot"
version = "0.1.0"
description = "Chatbot for Discord"
authors = ["Todd Birchard <toddbirchard@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
discord = "*"
requests = "*"
loguru = "*"
python-dotenv = "*"
pytz = "^2020.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
